name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  CI: "true"
  DO_NOT_TRACK: "1"
  TURBO_TELEMETRY_DISABLED: "1"
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: publish

    steps:
      # - name: Check NPM_TOKEN presence
      #   run: |
      #     if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
      #       echo "NPM_TOKEN is missing!"
      #       exit 1
      #     else
      #       echo "NPM_TOKEN is available."
      #     fi

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org/"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      # - name: Create .npmrc
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     version: bun run version
      #     publish: bun run publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
